### ISSUE TITLE
Block ChatMessage

### ISSUE THREAD

**Issue by TheOnlyMc** [shadowIdeas/shadowAPI2#6]
Guten Tag,
gibt es die Möglichkeit das die eingegebene Chatnachricht geblockt wird?
Also angenommen ich tippe: /help + Eingabetaste
gibt es nun die möglichkeit das abzufragen das ich das eingegeben habe, bevor es an den server gesendet wird, ich aber zb. ein Chat.Send("..."); ausführe?

**Comment by JohnnyCrazy** [comment]
Hi,

Dies ist aktuell nicht möglich und wird auch nicht in diesem Projekt kommen.
Allerdings arbeiten wir an einem weiteren Projekt (shadowInput), was dies unterstützen wird.

MfG
Johnny

**Comment by Levitas** [comment]
Hi,

Da es momentan nicht möglich ist und wie Johnny schon sagt nicht geplant ist, schließe ich das hier mal :D 

MfG
